substitutions:
  _PROJECT_ID: "your-project-id"
  _REGION: "us-central1"
  _TASKS: "hello-world"
  _TASK_MODULES: "hello_world"
  _SERVICE_ACCOUNT: "tasks-jobs-sa"
  _REPOSITORY_NAME: "tasks-images"
  _CORE_IMAGE: "tasks-core"
  _VERSION: "0.1.0"
  _FIRESTORE_DATABASE: "(default)"

steps:
  # Step 1: Build Core Image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY_NAME/$_CORE_IMAGE:latest',
      '-t', '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY_NAME/$_CORE_IMAGE:$_VERSION',
      '-f', './core/Dockerfile', './core'
    ]

  # Step 2: Push Core Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY_NAME/$_CORE_IMAGE:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY_NAME/$_CORE_IMAGE:$_VERSION']


  # Step 3-6: Iterate Over Tasks
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        i=0
        for TASK in $(echo $_TASKS | tr "," " "); do
          echo "Processing $$TASK..."
          TASK_MODULE=$(echo $_TASK_MODULES | tr "," " " | cut -d " " -f $$((i+1)))

          # Step 1: Build Task Image
          docker build \
            --build-arg CORE_IMAGE=$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY_NAME/$_CORE_IMAGE:latest \
            --build-arg TASK_MODULE=$$TASK_MODULE \
            -t $_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY_NAME/tasks-$$TASK:latest \
            -t $_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY_NAME/tasks-$$TASK:$_VERSION \
            -f ./$$TASK/Dockerfile ./$$TASK

          # Step 2: Push Task Image
          docker push $_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY_NAME/tasks-$$TASK:latest
          docker push $_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY_NAME/tasks-$$TASK:$_VERSION

          # Step 3: Deploy Task to Cloud Run Job
          gcloud run jobs deploy tasks-$$TASK-cr \
            --image=$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY_NAME/tasks-$$TASK:latest \
            --service-account=$_SERVICE_ACCOUNT@$_PROJECT_ID.iam.gserviceaccount.com \
            --region=$_REGION \
            --max-retries=1 \
            --set-env-vars="FIRESTORE_PROJECT_ID=$_PROJECT_ID,FIRESTORE_DATABASE=$_FIRESTORE_DATABASE,TASK_PROJECT_ID=$_PROJECT_ID,TASK_REGION=$_REGION,TASK_JOB_NAME=tasks-$$TASK-cr"

          # Step 4: Register Task by Calling Cloud Function
          gcloud run jobs execute tasks-$$TASK-cr \
            --region=$_REGION \
            --wait \
            --update-env-vars=TASK_COMMAND=tasks-register
          i=$$((i+1))
        done
