substitutions:
  _PROJECT_ID: ""
  _VERSION: "0.1.0"
  _REGION: "us-central1"
  _FIRESTORE_DATABASE: "(default)"
  _REPOSITORY_NAME: "tasks-images"
  _IMAGE_NAME: "tasks-api-server"
  _SERVICE_ACCOUNT: "tasks-api-sa"
  _SERVICE_ACCOUNT_JOBS: "tasks-jobs-sa"

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '$_REGION-docker.pkg.dev/${_PROJECT_ID}/$_REPOSITORY_NAME/$_IMAGE_NAME:${_VERSION}',
      '-t', '$_REGION-docker.pkg.dev/${_PROJECT_ID}/$_REPOSITORY_NAME/$_IMAGE_NAME:latest',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '$_REGION-docker.pkg.dev/${_PROJECT_ID}/$_REPOSITORY_NAME/$_IMAGE_NAME:$_VERSION'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '$_REGION-docker.pkg.dev/${_PROJECT_ID}/$_REPOSITORY_NAME/$_IMAGE_NAME:latest'
    ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run',
      'deploy',
      '$_IMAGE_NAME',
      '--image', '$_REGION-docker.pkg.dev/${_PROJECT_ID}/$_REPOSITORY_NAME/$_IMAGE_NAME:latest',
      '--region', '$_REGION',
      '--platform', 'managed',
      '--service-account', '$_SERVICE_ACCOUNT@${_PROJECT_ID}.iam.gserviceaccount.com',
      '--set-env-vars', 'FIRESTORE_DATABASE=$_FIRESTORE_DATABASE,FIRESTORE_PROJECT_ID=${_PROJECT_ID},TASKS_PROJECT_ID=${_PROJECT_ID},TASKS_LOCATION=$_REGION,TASKS_SERVICE_ACCOUNT_EMAIL=$_SERVICE_ACCOUNT_JOBS@${_PROJECT_ID}.iam.gserviceaccount.com'
    ]